version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build:
      context: ./config
      dockerfile: $PWD/Dockerfile-java-config
      args:
        JAR_FILE: ./target/config.jar
        PORT: 8888
    ports:
      - 8888:8888


  registry:
    build:
      context: ./registry
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/registry.jar
        PORT: 8761

  gateway:
    build:
      context: ./gateway
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/gateway.jar
        PORT: 4000

  auth-service:
    build:
      context: ./auth-service
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/auth-service.jar
        PORT: 5000
    ports:
      - 5000:5000

  auth-mongodb:
    build: mongodb
    ports:
      - 25000:27017

  account-service:
    build:
      context: ./account-service
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/account-service.jar
        PORT: 6000
    ports:
      - 6000:6000

  account-mongodb:
    build: mongodb
    ports:
      - 26000:27017

  statistics-service:
    build:
      context: ./statistics-service
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/statistics-service.jar
        PORT: 7000
    ports:
      - 7000:7000

  statistics-mongodb:
    build: mongodb
    ports:
      - 27000:27017

  notification-service:
    build:
      context: ./notification-service
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/notification-service.jar
        PORT: 8000
    ports:
      - 8000:8000

  notification-mongodb:
    build: mongodb
    ports:
      - 28000:27017

  monitoring:
    build:
      context: ./monitoring
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/monitoring.jar
        PORT: 8080


  turbine-stream-service:
    build:
      context: ./turbine-stream-service
      dockerfile: $PWD/Dockerfile-java
      args:
        JAR_FILE: ./target/turbine-stream-service.jar
        PORT: 8989
