FROM openjdk:8-jdk-alpine
VOLUME /tmp

ARG JAR_FILE
ARG PORT

COPY ${JAR_FILE} app.jar
RUN apk add curl --no-cache

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

EXPOSE ${PORT}