FROM openjdk:8-jdk-alpine
VOLUME /tmp

ARG JAR_FILE

COPY ${JAR_FILE} app.jar
RUN apk add curl --no-cache

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

EXPOSE $PORT

HEALTHCHECK --interval=30s --timeout=30s CMD curl -f http://localhost:8888/actuator/health || exit 1

EXPOSE 8888