apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-mongodb
  namespace: default
spec:
  selector:
    matchLabels:
      app: auth-mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
      - name: auth-mongodb
        image: microservdemo/piggymetrics-auth-mongodb:{{IMG_VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        env:
          - name: MONGODB_PASSWORD
            value: "{{MONGODB_PASSWORD}}"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: auth-mongodb
  sessionAffinity: None
  type: ClusterIP
