apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: microservdemo/piggymetrics-gateway:{{IMG_VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: "{{CONFIG_SERVICE_PASSWORD}}"
        - name: JAVA_TOOL_OPTIONS
          value: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1'
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: http

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - name: http
    port: 4000
    protocol: TCP
    targetPort: 4000
    nodePort: 31234
  selector:
    app: gateway
  sessionAffinity: None
#  type: ClusterIP
  type: NodePort