apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: notification-service
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: microservdemo/piggymetrics-notification-service:{{IMG_VERSION}}
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: CONFIG_SERVICE_PASSWORD
              value: "{{CONFIG_SERVICE_PASSWORD}}"
            - name: MONGODB_PASSWORD
              value: "{{MONGODB_PASSWORD}}"
            - name: NOTIFICATION_SERVICE_PASSWORD
              value: "{{NOTIFICATION_SERVICE_PASSWORD}}"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - name: http
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: notification-service
  sessionAffinity: None
  type: ClusterIP
