apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
  namespace: default
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: microservdemo/piggymetrics-registry:{{IMG_VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8761
        env:
        - name: CONFIG_SERVICE_PASSWORD
          value: "{{CONFIG_SERVICE_PASSWORD}}"
        - name: JAVA_TOOL_OPTIONS
          value: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1'
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
  - name: http
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: registry
  sessionAffinity: None
  type: ClusterIP
