apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: statistics-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: statistics-service
  replicas: 1
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
      - name: statistics-service
        image: microservdemo/piggymetrics-statistics-service:{{IMG_VERSION}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
            name: http
        env:
          - name: CONFIG_SERVICE_PASSWORD
            value: "{{CONFIG_SERVICE_PASSWORD}}"
          - name: MONGODB_PASSWORD
            value: "{{MONGODB_PASSWORD}}"
          - name: STATISTICS_SERVICE_PASSWORD
            value: "{{STATISTICS_SERVICE_PASSWORD}}"
          - name: JAVA_TOOL_OPTIONS
            value: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1'
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 256Mi
#        readinessProbe:
#          httpGet:
#            path: /actuator/health
#            port: http

---
apiVersion: v1
kind: Service
metadata:
  name: statistics-service
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: statistics-service
  sessionAffinity: None
  type: ClusterIP
